// @ts-nocheck
/**
 * Scripts
 * Inject client-side code onto a BigCommere storefront. To learn more about scripts, see [Scripts API](/api-docs/store-management/scripts).   ## OAuth Scopes | UI Name                                      | Permission | Parameter                                     | |----------------------------------------------|------------|-----------------------------------------------| | Checkout Content1                             | modify     | `store_content_checkout`                      | | Checkout Content1                             | read-only  | `store_content_checkout_read_only`            | | Content                                       | modify     | `store_v2_content`                            | | Content                                       | read-only  | `store_v2_content_read_only`                  |  1. `Checkout Content` scopes are required to create or read scripts on the checkout page.  For more information on OAuth Scopes, see [Authentication](/api-docs/getting-started/authentication/rest-api-authentication#oauth-scopes).  ## Authentication  Requests can be authenticated by sending an`access_token` via `X-Auth-Token` HTTP header:  ```http host: api.bigcommerce.com Accept: application/json X-Auth-Token: {access_token} ```  |Header|Parameter|Description| |-|-|-| |`X-Auth-Token`|`access_token`|Obtained by creating an API account or installing an app in a BigCommerce control panel.|  For more information on Authenticating BigCommerce APIs, see [Authentication](/api-docs/getting-started/authentication).  ## Available Endpoints | Resource / Endpoint                     | Description                                                             | |-----------------------------------------|-------------------------------------------------------------------------| | Scripts                                 | Add client-side code to a store                                         |
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Pagination1Links } from '../models/Pagination1Links';
import { HttpFile } from '../http/http';

/**
* Data about the response, including pagination and collection totals.
*/
export class Pagination {
    /**
    * Total number of items in the result set. 
    */
    'total'?: number;
    /**
    * Total number of items in the collection response. 
    */
    'count'?: number;
    /**
    * The amount of items returned in the collection per page, controlled by the limit parameter. 
    */
    'per_page'?: number;
    /**
    * The page you are currently on within the collection. 
    */
    'current_page'?: number;
    /**
    * The total number of pages in the collection. 
    */
    'total_pages'?: number;
    'links'?: Pagination1Links;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "per_page",
            "baseName": "per_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "current_page",
            "baseName": "current_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "total_pages",
            "baseName": "total_pages",
            "type": "number",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Pagination1Links",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Pagination.attributeTypeMap;
    }

    public constructor() {
    }
}

